import { Router } from 'express';
import { router as authController } from '../controllers/auth.controller.js';
import { router as TodoController } from '../controllers/todo.controller.js';
import { router as PostsController } from '../controllers/posts.controller.js';
import { router as UserController } from '../controllers/user.controller.js';
import { authorizeUser } from '../helpers/auth.helper.js';
const router = Router();
router.use('/auth', authController);
router.use('/todo', authorizeUser, TodoController);
router.use('/posts', authorizeUser, PostsController);
router.use('/users', authorizeUser, UserController);
export { router };
